# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Where things are
# source:       .
# destination:  ./_site
# plugins_dir:  ./_plugins
# layouts_dir:  ./_layouts
# data_dir:     ./_data
# includes_dir: ./_includes
# collections:  null

# Handling Reading
safe:         false
exclude:      []
keep_files:   [".git"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Site settings
title:             Блог об IT
email:             batazor111@gmail.com
description:       Блог о программировании, IT и DevOps
url:               "http://batazor.ru"
twitter_username:  batazor
github_username:   batazor

# Filtering Content
show_drafts:       null
limit_posts:       0
future:            false
unpublished:       false

# Plugins
whitelist:         []
gems:              ["emoji_for_jekyll"]

# Conversion
markdown:          kramdown
highlighter:       rouge
lsi:               false
excerpt_separator: "\n\n"
incremental:       false

# Serving
detach:            false
port:              4000
host:              127.0.0.1
baseurl:           ""

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
